# -*- coding: utf-8 -*-
"""Proyecto_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lURF_yXz1J9eNy5GKwewk9pW3CNgzt7

#***DESCRIPCIÓN GENERAL DEL PROYECTO***

Una plataforma de comercio electrónico como Amazon requiere implementar modelos de Machine Learning para analizar el comportamiento de sus ventas y segmentar sus órdenes de compra, con el fin de optimizar la toma de decisiones estratégicas.

En este contexto, el presente proyecto tiene como objetivo aplicar dos modelos de analítica avanzada sobre el dataset Amazon Sales Dataset, utilizando dos enfoques complementarios:

- **Modelo de Clustering K-Means:** Permite segmentar las órdenes de compra en grupos homogéneos a partir de variables comerciales clave como precio, descuento, cantidad vendida, rating del producto e ingreso generado.
- **Modelo de Redes Neuronales (ADALINE):** Permite predecir el ingreso total (total_revenue) generado por cada transacción en función de sus variables comerciales y de comportamiento.

**DESCRIPCIÓN BASE DE DATOS**

La base de datos Amazon Sales Dataset contiene 50,000 registros de transacciones de ventas realizadas en la plataforma. Cada registro representa una orden de compra e incluye información sobre el producto, el cliente, el método de pago, los descuentos aplicados y los ingresos generados, lo que la convierte en una fuente relevante para el análisis del comportamiento comercial en entornos de e-commerce.

**VARIABLES UTILIZADAS**

Para el desarrollo de los modelos, se emplean las siguientes variables:

- **Price:** Precio original del producto (USD)
- **Discount_percent:** Porcentaje de descuento aplicado a la orden
- **Quantity_sold:** Número de unidades vendidas
- **Rating:** Calificación del producto por parte del cliente (1.0 – 5.0)
- **Total_revenue:** Ingreso total generado por la transacción (variable objetivo del modelo de pronóstico)

Adicionalmente, se incluye una variable categórica clave:

- **Product_category:** Permite clasificar los registros según el tipo de producto, facilitando el análisis y la interpretación de los segmentos obtenidos.

**IMPORTANCIA TOMA DE DECISIONES**

En el entorno del comercio electrónico, la capacidad de interpretar y predecir el comportamiento de las ventas es un activo estratégico fundamental. Esta base de datos permite a la organización tomar decisiones basadas en evidencia en tres dimensiones críticas:

- **Optimización de precios y descuentos:** Permite identificar niveles de descuento que maximicen los ingresos sin afectar negativamente los márgenes.
- **Segmentación de mercado:** Facilita el diseño de estrategias diferenciadas de marketing, inventario y logística a partir de patrones de compra.
- **Pronóstico de ingresos:** Permite anticipar el comportamiento financiero, mejorando la planeación, el flujo de caja y la asignación de recursos.

**BENEFICIOS DE LOS MODELOS SELECCIONADOS**

- **K-Means:** Permite identificar patrones ocultos en los datos, agrupando transacciones con comportamiento similar a partir de variables numéricas como price, discount_percent, quantity_sold y total_revenue. Esto facilita la segmentación estratégica y la personalización de decisiones comerciales relacionadas con pricing, promociones e inventario.

- **Redes Neuronales (ADALINE):** Permiten modelar relaciones lineales entre las variables de entrada y el ingreso total, ofreciendo una herramienta eficiente y computacionalmente simple para el pronóstico. Esto facilita la estimación del impacto de variables comerciales sobre los ingresos y apoya la planificación financiera.

**ENFOQUE INTEGRADO DEL ANÁLISIS**

La combinación de K-Means y ADALINE permite no solo segmentar el comportamiento de las transacciones, sino también predecir el desempeño económico dentro de cada segmento identificado, fortaleciendo la toma de decisiones estratégicas basadas en datos.

0. Se procede con la carga de las librerías de trabajo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns               #Herramienta para gráficas estadísticas
from sklearn.cluster import KMeans  #Herramienta de Clustering K-Means
import tensorflow as tf             #Framework de Redes Neuronales

"""1. Se cargan datos de trabajo"""

nxl = '/content/amazon_sales_dataset.csv'
XDB = pd.read_csv(nxl)
XD = XDB[['price', 'discount_percent','quantity_sold', 'rating']] #Datos de entrada (variables independientes)
yd = XDB['total_revenue'] #Variable de salida (revenue total)
#Determinamos la correlación entre las variables de análisis
XDB2 = XDB[['price', 'discount_percent', 'quantity_sold', 'rating', 'total_revenue']].copy() #Subconjunto con variables relevantes
sns.heatmap (XDB2.corr(), annot=True)

"""2. Se procede con la implementación del modelo KMeans"""

np.random.seed (42) #Esto permite generar las mismas semillas para todos
NC= 5 #Segmentos o perfiles de clientes
mKm= KMeans (n_clusters= NC, random_state=42)
mKm.fit (XD, yd) #El modelo busca la mejor relación entre la entrada y la salida

#Obtenemos las características de cada grupo
#Representa los perfiles de las personas mkm.cluster_centers_ que encontró el modelo
Tabla=pd.DataFrame(mKm.cluster_centers_, columns=XD.columns)
display(Tabla)

#Para saber la distribución de órdenes por segmento o perfil
ydp=mKm.labels_ #Esto me indica en que cluster queda clasificado cada órden
NDc= np.bincount(ydp) #Número de datos por segmento
print("El número de datos por cluster es:", NDc)

"""3. Porcentajes de Revenue Alto vs Revenue Bajo por Cluster"""

XDB2['Cluster'] = ydp
display(XDB2)

#Determinar el Revenue promedio y total por Cluster
NApr = XDB2.groupby('Cluster').agg({"total_revenue": "mean"})   #Revenue promedio por segmento
NPrn = XDB2.groupby('Cluster').agg({"total_revenue": "sum"})    #Revenue total por segmento

#Para visualizar los resultados por cluster
df2 = pd.DataFrame(np.column_stack([NApr, NPrn]), columns=['Revenue_Promedio', 'Revenue_Total'])
display(df2)

"""4. ¿Qué pasa si aparece una nueva orden? Price: $250, Discount: 20%, Quantity_sold: 3, Rating: 4.5"""

nueva_orden = np.array([250, 20, 3, 4.5]) #Price, Discount, Quantity, Rating
ydp = mKm.predict(nueva_orden.reshape(1, -1)) #Reshape: quitarle la estructura al modelo
NC1 = ydp[0]
print("La nueva orden pertenece al cluster:", ydp)
print("El Revenue promedio de su cluster es:", NApr.iloc[NC1].values[0])
print("El Revenue total de su cluster es:", NPrn.iloc[NC1].values[0])

"""5. Se procede con la gráfica de los clusters utilizando las variables Price y Total_revenue"""

centers = mKm.cluster_centers_
prc = np.array(XD['price'])
rev = np.array(XDB['total_revenue'])

plt.figure()
plt.scatter(prc, rev, c=mKm.labels_, cmap='rainbow')


plt.scatter(centers[:, 0], centers[:, 2], c='black', s=4500, alpha=0.5)

plt.xlabel('Price')
plt.ylabel('Total Revenue')

for i, center in enumerate(centers):
    plt.text(center[0], center[2], str(i), color='white', fontsize=12, ha='center', va='center')

plt.show()

"""***Análisis de Resultados - K-Means***

En el Heatmap se observa que la mayor correlación se presenta entre las variables price y total_revenue (0.71), lo que indica que el precio del producto es el principal determinante del ingreso generado. Adicionalmente, la variable quantity_sold (0.59) también influye significativamente en el revenue, evidenciando que Amazon puede incrementar sus ingresos tanto mediante estrategias de precios como aumentando el volumen de ventas. Por el contrario, variables como rating y discount_percent no presentan una relación significativa, lo que sugiere que no son factores determinantes en la generación de ingresos.

De acuerdo con los clusters generados por el modelo K-Means, se identifican 5 segmentos de órdenes de compra con comportamientos diferenciados. Esto le permite a Amazon reconocer que existen distintos modelos de generación de ingresos: algunos basados en productos de alto valor, y otros en alto volumen de ventas. Esta segmentación facilita la toma de decisiones como ajustar precios, definir estrategias de promoción y optimizar la gestión de inventario según el tipo de producto.

Finalmente, al analizar una nueva orden, el modelo permite clasificarla dentro de un segmento específico y estimar su comportamiento esperado en términos de revenue, lo que permite anticipar su desempeño comercial.

#**PARTE 2: REDES NEURONALES**

0. Se procede con la carga de las librerías de trabajo
"""

import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns #Esto es para gráficas estadísticas

"""1. Se procede con la carga de los datos"""

#Datos de Entrada (price, discount_percent, quantity_sold, rating)
XD = np.array(XDB[['price', 'discount_percent','quantity_sold', 'rating']]) #Matriz de variables independientes
#Variable de Salida - Total Revenue
yd = np.array(XDB['total_revenue']) #Valor deseado - Recompensa para la red

#'''''''''''''''''''''''''''''''''''''''
#Normalización de las Variables - Máximo
#'''''''''''''''''''''''''''''''''''''''
XDn = XD / XD.max(axis=0) #Dividimos cada variable por su máximo por columna
ydn = yd / yd.max() #Dividimos por el máximo

"""2. Se procede con la configuración del modelo neuronal (ADALINE - Adaptive Linear) de una sola regresión

"""

np.random.seed(42)                              #El modelo inicia con los mismos números aleatorios
mnn = tf.keras.models.Sequential()             #La estructura general de una red neuronal
mnn.add(tf.keras.layers.Dense(units=1, input_shape=(4,), use_bias=True))  #Capa de entrada
mnn.compile(optimizer='sgd', loss='mse')        #sgd: derivada del error, mse: error cuadratico medio
mnn.summary()                                   #yrk Respuesta de la red similar valor deseado ydk

#Ajustamos el modelo
history = mnn.fit(XDn, ydn, epochs=100, verbose=1)
#¿Cuál es la respuesta final del modelo?
yp = mnn.predict(XDn)

"""3. Se procede a evaluar el comportamiento del modelo"""

MC = np.column_stack((yd, yp * yd.max()))       #Se desnormaliza la predicción para comparar
MC = pd.DataFrame(MC)
MC.columns = ['yd-deseado', 'yr-respuesta']
print('Correlación Modelo - Total Revenue:')
print(MC.corr())                                 #Una correlación cercana a 1 indica buen ajuste del modelo

#Gráfica de curvas: deseado vs predicho (primeros 100 registros para mejor visualización)
plt.figure()
plt.plot(ydn[0:100,], color='red', label='ydeseado')
plt.plot(yp[0:100,], color='blue', label='yrespuesta')
plt.title('Total Revenue: Deseado vs Predicho')
plt.legend()
plt.grid()
plt.show()

#Gráfica de dispersión para ver qué tan concentrados están los puntos alrededor de la diagonal
plt.figure()
plt.scatter(ydn, yp)                             #Puntos cercanos a la diagonal = buen modelo
plt.title('Dispersión - Total Revenue')
plt.xlabel('yd - Deseado')
plt.ylabel('yp - Predicho')
plt.grid()
plt.show()

#Gráfico de distribuciones: compara la forma de la curva deseada vs la predicha
plt.figure()
sns.kdeplot(ydn, fill=True, color='red', label='ydeseado')          #Distribución real
sns.kdeplot(yp.flatten(), fill=True, color='blue', label='ypredicho') #Distribución predicha
plt.title('Distribución - Total Revenue')
plt.legend()
plt.grid()
plt.show()

"""4. Se pone en funcionamiento el modelo"""

XDp = np.array([250, 20, 3, 4.5]) #Price, Discount, Quantity, Rating
ydpp = mnn.predict((XDp / XD.max(axis=0)).reshape(1, -1))
print("Esta orden tiene un Revenue Total predicho de:", ydpp * yd.max())

#Cuales son las conexiones nerviosas
W = mnn.get_weights()
print(W)

"""***ANÁLISIS DE RESULTADOS - REDES NEURONALES***

El modelo de redes neuronales (ADALINE) obtuvo una correlación de 0.93 entre el valor real y el predicho, lo que indica un alto nivel de precisión en la estimación del total_revenue. Esto permite a Amazon predecir con confiabilidad el ingreso esperado de nuevas órdenes de compra.

El análisis de los pesos del modelo muestra que la variable price es el principal factor que impacta el revenue, seguida por quantity_sold, lo que confirma los resultados observados en el análisis de correlación. Por su parte, discount_percent presenta un efecto negativo, indicando que mayores descuentos pueden reducir el ingreso, mientras que rating no tiene un impacto significativo.

Al aplicar el modelo a una nueva orden, se obtiene una estimación del revenue coherente con sus características, lo que permite a Amazon anticipar el resultado económico de sus decisiones comerciales antes de ejecutarlas.

#**CONCLUSIÓN GENERAL**

Los resultados obtenidos permiten a Amazon comprender y predecir el comportamiento de sus ventas desde dos enfoques complementarios.

El modelo K-Means facilita la identificación de diferentes perfiles de generación de ingresos, permitiendo diseñar estrategias específicas para cada segmento. Por su parte, el modelo ADALINE permite predecir el revenue de nuevas órdenes con alta precisión, apoyando la planeación financiera y la toma de decisiones en tiempo real.

En conjunto, estos modelos permiten a Amazon pasar de un análisis descriptivo a un enfoque predictivo, optimizando decisiones de pricing, inventario y estrategias comerciales, y generando una ventaja competitiva basada en el uso de analítica de datos.
"""